version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo "currect commit $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - ls -lash
      - npm install
      - echo Build Static Assets...
      - npm run build-static
      - echo show build artifact files
      - ls -lash
  post_build:
    commands:
      - echo Done...